### ISSUE TITLE
TXTDoubleLabel warning message amendment

### ISSUE THREAD

**Issue by jobe1986** [letsdebug/letsdebug#20]
TXTDoubleLabel's description should probably clarify that this warning can be caused by having a TXT record for *.example.com. instead of just out assuming it is caused by a TXT record for _acme-challenge.example.com.example.com.

The actual test could possibly be amended to test for a TXT record with the exact name *.example.com. when testing dns-01 for example.com. however such a test doesn't itself rule out a double label.

**Comment by alexzorin** [comment]
i see what you mean.

This scenario can probably be filtered out by testing if 

`_acme-challenge._acme-challenge.example.org/TXT == random_string._acme-challenge.example.org/TXT`. I'll look into it.

**Comment by alexzorin** [comment]
I've deployed something that should help mitigate. The commit note is below.
 
Let me know what you think. It's not entirely foolproof but should catch most cases.

```
As described in #20, the TXTDoubleLabel warning would appear when
a zone contained a wildcard TXT record (not awfully common).

We will suppress this warning when we detect that the response
was created due to a wildcard record.

So this zone should generate a warning:

*.example.org				IN	TXT	300 "abc"
_acme-challenge.example.org.example.org	IN	TXT	300 "xxx"

But this shouldn't:

*.example.org				IN	TXT	300 "abc"
_acme-challenge.example.org		IN	TXT	300 "xxx"

Not should this:

*.example.org				IN	TXT	300 "abc"
```

**Comment by jobe1986** [comment]
Appears to work fine with the zone I experienced the warning with. And the logic you described seems appropriate to me.

For the record the *.example.org TXT record I have is actually a catch all SPF record. But either way the content shouldn't matter really. It is however extremely unlikely that somebody may have a *.example.org TXT record with the exact same value as an _acme-challenge so I don't see any flaws in your logic.
