### ISSUE TITLE
StatusNotOperational not working as expected.

### ISSUE THREAD

**Issue by sagarspatil** [letsdebug/letsdebug#25]
Please check the thread here - 
https://community.letsencrypt.org/t/let-s-encrypt-is-currently-experiencing-an-outage-please-try-again-in-some-time/125296/4

**Comment by alexzorin** [comment]
What was your expectation?

`StatusNotOperational` exists at the Warning severity level, along with a handful of other "soft" problems that do not necessarily indicate a real problem.

If you want only real problems, I would only pay attention to Error and Fatal severity problems.

I see where you are coming from, so I have updated the status.io checker to explicitly filter out the `200` `status_code`. It is oddly missing from https://kb.status.io/developers/status-codes/, but seems to be reserved for Planned Maintenance.

I wouldn't hold my breath for this tool to be intelligent enough to identify whether the issuance API is actually down or not. Outages are rarely so straightforward. For that reason, it's only a Warning.

**Comment by sagarspatil** [comment]
@alexzorin Thanks. That seem to have fixed the issue :)

**Comment by alexzorin** [comment]
Great!
