### ISSUE TITLE
no such result exists

### ISSUE THREAD

**Issue by millerthegorilla** [letsdebug/letsdebug#26]
Hi, I am following your instructions for the web api, and so I perform the following:

```curl --data '{"method":"http-01","domain":"cisles.duckdns.org"}' -H 'content-type: application/json' https://letsdebug.net```
which returns:

```{"Domain":"cisles.duckdns.org","ID":672185}```

When I then run :

```curl -H 'accept: application/json' https://letsdebug.net/letsdebug.net/672185```

I get :

```No such result exists.```

Although if I visit the letsdebug site at the following url:

```https://letsdebug.net/cisles.duckdns.org/672185```

I get a result - in this case I am expecting 'ANotWorking'.
I guess I am doing something wrong?

Edit....   I see now that I should use the following 

```curl -H 'accept: application/json' https://letsdebug.net/cisles.duckdns.org/672185```

I wonder if the docs could be a bit clearer for aging seniors like myself....    thanks anyway!

**Comment by alexzorin** [comment]
> I wonder if the docs could be a bit clearer for aging seniors like myself.... thanks anyway!

Yes, I can see how using the same domain for the API example would be pretty confusing. I've changed that. Thank you!
