### ISSUE TITLE
letsdebug does not report missing intermediate certs

### ISSUE THREAD

**Issue by matthewbaggett** [letsdebug/letsdebug#29]
Our application was behaving in Firefox and Chromium, but not in wget. 

Just by chance I realised it was a missing intermediate cert. I'd like to feature-request that it could also check for these.

**Comment by alexzorin** [comment]
It isn't my intention currently to detect issues that don't directly relate to:

>Let's Debug is a diagnostic tool/website to help figure out why you might not be able to issue a certificate

A misconfigured certificate chain isn't going to have any effect on certificate issuance attempts. 

There are other sites (like Qualys SSL Labs) which do a very good job of what you're asking for.

**Comment by matthewbaggett** [comment]
Fair enough. Would be cool if it did though!
