### ISSUE TITLE
Allow prefill of domain and validation-method

### ISSUE THREAD

**Issue by ralexander-phi** [letsdebug/letsdebug#31]
This is a great debugging tool, thanks for creating it!

I think it would be helpful if the httpHome route supported pre-filling the form from the URL. Other websites could build a URL with the user's domain and validation method baked in, the user would click it, see the pre-filled form, and then click Run Test without needing to manually enter their information.

I suggest adding these as URL parameters like: https://letsdebug.net/?prefill-domain=example.com&prefill-validation-method=http-01

If you're open to a PR for this idea I'd be happy to send one over.

**Comment by alexzorin** [comment]
Yeah, a PR sounds good. `method` and `domain` are already the names of the parameters for the `POST` endpoint, so let's do the same for the `GET` one.
