### ISSUE TITLE
binarie missing for cli since version 1.7.0

### ISSUE THREAD

**Issue by janus57** [letsdebug/letsdebug#45]
Hi,

Since the [v1.7.0](https://github.com/letsdebug/letsdebug/releases/tag/v1.7.0) the binarie "letsdebug-cli" is missing on the release page.

Best regards,
janus57

**Comment by GermanCoding** [comment]
Ah, yeah. We're using an automated release flow since 1.7.0 and it looks like we never added the cli to the automation builds. https://github.com/letsdebug/letsdebug/commit/9ee315471777035725d7f0d62708ef3dae9fe3b7.

**Comment by GermanCoding** [comment]
Fixed in https://github.com/letsdebug/letsdebug/releases/tag/v1.8.2
